### ISSUE TITLE
Where should we change VPN ports from 1194 to 8888???

### ISSUE THREAD

**Issue by cmydlarz** [Mohitsharma44/sonyc-backend#1]
@Mohitsharma44 Unsure where to change our VPN ports from `1194` to `8888` as our new VMS only have `8888` open for VPN use.  Here in `setup-openvpn.yml`: 
```
- hosts: docker_swarm_manager
  become: True
  serial: 1
  vars:
    - first_vpn_subnet: '192.168.200.0'
    - openvpn_port: '1194'
    - istest: 'true'
```

Also what should we change the `192.168.200.0` address to? Our new VMs IP addresses?
